import json

path = 'notebooks/kaggle_train.ipynb'
nb = json.load(open(path, encoding='utf-8'))

def cell(src):
    return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": src}

def md(src):
    return {"cell_type": "markdown", "metadata": {}, "source": src}

nb['cells'] = [
md("# Spot RL Training -- Kaggle\nTrain DQN generalist agent for AWS Spot Instance optimization."),

cell(
"# Step 1: Install dependencies\n"
"!pip install gymnasium torch numpy pandas pyyaml mlflow --quiet\n"
),

cell(
"# Step 2: Setup project path -- auto-detect & unzip dataset\n"
"import os, sys, shutil, glob, zipfile\n"
"\n"
"DST = '/kaggle/working'\n"
"DATASET_PATH = None\n"
"\n"
"for root in glob.glob('/kaggle/input/**', recursive=False):\n"
"    for dirpath, dirnames, filenames in os.walk(root):\n"
"        if 'envs' in dirnames and 'agents' in dirnames:\n"
"            DATASET_PATH = dirpath\n"
"            break\n"
"    if DATASET_PATH:\n"
"        break\n"
"\n"
"if DATASET_PATH is None:\n"
"    for root in glob.glob('/kaggle/input/**', recursive=False):\n"
"        for dirpath, dirnames, filenames in os.walk(root):\n"
"            for fname in filenames:\n"
"                if fname.endswith('.zip'):\n"
"                    zip_path = os.path.join(dirpath, fname)\n"
"                    extract_dir = os.path.join(DST, '_extracted')\n"
"                    os.makedirs(extract_dir, exist_ok=True)\n"
"                    with zipfile.ZipFile(zip_path, 'r') as zf:\n"
"                        zf.extractall(extract_dir)\n"
"                    for dp, dns, fns in os.walk(extract_dir):\n"
"                        if 'envs' in dns and 'agents' in dns:\n"
"                            DATASET_PATH = dp\n"
"                            break\n"
"                if DATASET_PATH:\n"
"                    break\n"
"            if DATASET_PATH:\n"
"                break\n"
"        if DATASET_PATH:\n"
"            break\n"
"\n"
"if DATASET_PATH is None:\n"
"    raise FileNotFoundError('Cannot find spot_rl code in /kaggle/input')\n"
"\n"
"print(f'Source: {DATASET_PATH}')\n"
"for folder in ['envs', 'agents', 'utils', 'experiments', 'data']:\n"
"    src = os.path.join(DATASET_PATH, folder)\n"
"    dst = os.path.join(DST, folder)\n"
"    if os.path.exists(src):\n"
"        if os.path.exists(dst):\n"
"            shutil.rmtree(dst)\n"
"        shutil.copytree(src, dst)\n"
"        print(f'  Copied {folder}/')\n"
"\n"
"for pkg in ['envs', 'agents', 'utils']:\n"
"    init = os.path.join(DST, pkg, '__init__.py')\n"
"    if not os.path.exists(init):\n"
"        open(init, 'w').close()\n"
"\n"
"sys.path.insert(0, DST)\n"
"print('Setup complete')\n"
),

cell(
"# Step 3: Verify imports\n"
"import numpy as np\n"
"import torch\n"
"import pickle\n"
"from envs.spot_orchestrator_env import SpotOrchestratorEnv\n"
"from envs.mixed_scenario_env import MixedScenarioEnv\n"
"from envs.instance_catalog import STATE_DIM\n"
"from envs.action_schema import N_ACTIONS, OPERATION_NAMES\n"
"from agents.dqn_agent import DQNAgent\n"
"print(f'PyTorch: {torch.__version__}')\n"
"print(f'State dim: {STATE_DIM}, Action dim: {N_ACTIONS}')\n"
"print(f'Device: {\"cuda\" if torch.cuda.is_available() else \"cpu\"}')\n"
),

cell(
"# Step 4: Check GPU\n"
"import torch\n"
"num_gpus = torch.cuda.device_count()\n"
"print(f'GPUs available: {num_gpus}')\n"
"for i in range(num_gpus):\n"
"    print(f'  GPU {i}: {torch.cuda.get_device_name(i)}')\n"
"device0 = 'cuda:0' if num_gpus >= 1 else 'cpu'\n"
"print(f'Training device: {device0}')\n"
),

cell(
"# Step 5: Setup env + agent\n"
"from envs.mixed_scenario_env import MixedScenarioEnv\n"
"from envs.instance_catalog import STATE_DIM\n"
"from envs.action_schema import N_ACTIONS\n"
"from agents.dqn_agent import DQNAgent\n"
"import inspect\n"
"\n"
"_params = list(inspect.signature(DQNAgent.__init__).parameters.keys())\n"
"print(f'DQNAgent params: {_params}')\n"
"\n"
"SCENARIOS = {\n"
"    'stable':        'data/processed/multipool_stable.csv',\n"
"    'volatile':      'data/processed/multipool_volatile.csv',\n"
"    'spike':         'data/processed/multipool_spike.csv',\n"
"    'az_divergence': 'data/processed/multipool_az_divergence.csv',\n"
"}\n"
"WORKLOAD_CFG = {'base_arrival_rate': 15.0, 'peak_multiplier': 2.0, 'avg_job_duration': 3}\n"
"\n"
"env = MixedScenarioEnv(scenario_paths=SCENARIOS, max_steps=168, workload_config=WORKLOAD_CFG, seed=42)\n"
"\n"
"_lr_key = 'learning_rate' if 'learning_rate' in _params else 'lr'\n"
"_tu_key = 'target_update_freq' if 'target_update_freq' in _params else 'target_update'\n"
"\n"
"agent_cfg = {\n"
"    'state_dim':    STATE_DIM,\n"
"    'action_dim':   N_ACTIONS,\n"
"    'hidden_dim':   512,\n"
"    'network_type': 'factored',\n"
"    _lr_key:        3e-4,\n"
"    'gamma':        0.99,\n"
"    'batch_size':   256,\n"
"    'buffer_size':  500000,\n"
"    'epsilon_start': 1.0,\n"
"    'epsilon_end':   0.05,\n"
"    'epsilon_decay': 300000,\n"
"    _tu_key:        500,\n"
"}\n"
"agent = DQNAgent(**agent_cfg, device=device0)\n"
"print(f'Env: obs={env.observation_space.shape}, act={env.action_space.n}')\n"
"print(f'Agent: {agent_cfg[\"network_type\"]} | params={sum(p.numel() for p in agent.q_network.parameters()):,}')\n"
),

cell(
"# Step 5b: MLflow setup -- credentials from Kaggle Secrets\n"
"import os, mlflow\n"
"try:\n"
"    from kaggle_secrets import UserSecretsClient\n"
"    secrets = UserSecretsClient()\n"
"    mlflow_user = secrets.get_secret('MLFLOW_USERNAME')\n"
"    mlflow_pass = secrets.get_secret('MLFLOW_PASSWORD')\n"
"    os.environ['AWS_ACCESS_KEY_ID']     = secrets.get_secret('AWS_ACCESS_KEY_ID')\n"
"    os.environ['AWS_SECRET_ACCESS_KEY'] = secrets.get_secret('AWS_SECRET_ACCESS_KEY')\n"
"\n"
"    MLFLOW_URI = f'https://{mlflow_user}:{mlflow_pass}@mlflow.holoc.id.vn'\n"
"    mlflow.set_tracking_uri(MLFLOW_URI)\n"
"    mlflow.set_experiment('spot-rl-generalist')\n"
"    mlflow.enable_system_metrics_logging()\n"
"\n"
"    client = mlflow.tracking.MlflowClient()\n"
"    client.search_experiments()\n"
"    print('MLflow connected: mlflow.holoc.id.vn')\n"
"    print('System metrics logging: ENABLED (CPU/RAM/GPU)')\n"
"    print(f'S3 artifact store ready: {bool(os.environ.get(\"AWS_ACCESS_KEY_ID\"))}')\n"
"except Exception as e:\n"
"    print(f'MLflow unavailable: {e}')\n"
"    MLFLOW_URI = None\n"
),

cell(
"# Step 5c: (OPTIONAL) Resume from checkpoint\n"
"# Set RESUME_CHECKPOINT to .pth path in Kaggle input to continue training\n"
"# Example: '/kaggle/input/spot-rl-models/best_mixed_v5.pth'\n"
"RESUME_CHECKPOINT = None\n"
"SAVE_DIR = '/kaggle/working/models'\n"
"import os; os.makedirs(SAVE_DIR, exist_ok=True)\n"
"\n"
"if RESUME_CHECKPOINT:\n"
"    agent.load(RESUME_CHECKPOINT)\n"
"    print(f'Resumed: {RESUME_CHECKPOINT}')\n"
"    print(f'  epsilon={agent.epsilon:.4f}  steps={agent.steps_done:,}')\n"
"else:\n"
"    print('Fresh training')\n"
),

cell(
"# Step 6: Training -- generalist agent + prioritized scenario sampling + MLflow\n"
"import time, pickle, os, mlflow\n"
"import numpy as np\n"
"from collections import defaultdict\n"
"\n"
"if 'MLFLOW_URI' not in dir():\n"
"    MLFLOW_URI = None\n"
"\n"
"NUM_EPISODES = 5000\n"
"PATIENCE     = 600\n"
"MIN_EPISODES = 2000\n"
"PRINT_EVERY  = 100\n"
"LOG_EVERY    = 10\n"
"os.makedirs(SAVE_DIR, exist_ok=True)\n"
"\n"
"def model_score(costs, slas, window=200):\n"
"    if len(costs) < window:\n"
"        return -float('inf')\n"
"    recent_cost = np.mean(costs[-window:])\n"
"    recent_sla  = np.mean(slas[-window:])\n"
"    if recent_sla < 0.95:\n"
"        return -1e6 + recent_sla * 1e5\n"
"    return -recent_cost\n"
"\n"
"rewards_history, loss_history = [], []\n"
"cost_history, sla_history, eps_history = [], [], []\n"
"scenario_history = []\n"
"per_scn_cost = defaultdict(list)\n"
"per_scn_sla  = defaultdict(list)\n"
"\n"
"best_score = -float('inf')\n"
"best_cost = best_sla = best_reward = None\n"
"no_improve_count = 0\n"
"start_time = time.time()\n"
"\n"
"run_name = f'resume-ep{agent.steps_done//168}' if RESUME_CHECKPOINT else 'generalist-prio'\n"
"run_ctx = mlflow.start_run(run_name=run_name) if MLFLOW_URI else None\n"
"if run_ctx:\n"
"    mlflow.log_params({\n"
"        **{k: v for k, v in agent_cfg.items() if not isinstance(v, (list, dict))},\n"
"        'num_episodes': NUM_EPISODES,\n"
"        'scenarios': ','.join(SCENARIOS.keys()),\n"
"        'network_params': sum(p.numel() for p in agent.q_network.parameters()),\n"
"        'prioritized_scenario_sampling': True,\n"
"        'resumed_from': RESUME_CHECKPOINT or 'scratch',\n"
"        'resume_epsilon': agent.epsilon,\n"
"        'resume_steps': agent.steps_done,\n"
"    })\n"
"\n"
"try:\n"
"    for episode in range(NUM_EPISODES):\n"
"        obs, info = env.reset()\n"
"        scn = info['scenario']\n"
"        ep_reward, ep_losses = 0.0, []\n"
"\n"
"        for step in range(168):\n"
"            mask = env.get_action_mask()\n"
"            action = agent.select_action(obs, training=True, action_mask=mask)\n"
"            next_obs, reward, term, trunc, info = env.step(action)\n"
"            done = term or trunc\n"
"            agent.store_transition(obs, action, reward, next_obs, done)\n"
"            loss = agent.train_step()\n"
"            if loss is not None:\n"
"                ep_losses.append(loss)\n"
"            ep_reward += reward\n"
"            obs = next_obs\n"
"            if done:\n"
"                break\n"
"\n"
"        ep_cost = info.get('cost', 0)\n"
"        ep_sla  = info.get('sla_compliance', 0)\n"
"        ep_loss = np.mean(ep_losses) if ep_losses else 0.0\n"
"\n"
"        rewards_history.append(ep_reward)\n"
"        loss_history.append(ep_loss)\n"
"        eps_history.append(agent.epsilon)\n"
"        cost_history.append(ep_cost)\n"
"        sla_history.append(ep_sla)\n"
"        scenario_history.append(scn)\n"
"        per_scn_cost[scn].append(ep_cost)\n"
"        per_scn_sla[scn].append(ep_sla)\n"
"\n"
"        if ep_loss > 0:\n"
"            env.update_scenario_loss(scn, ep_loss)\n"
"\n"
"        if episode >= 200:\n"
"            score = model_score(cost_history, sla_history, window=200)\n"
"            if score > best_score + 0.5:\n"
"                best_score  = score\n"
"                best_cost   = np.mean(cost_history[-200:])\n"
"                best_sla    = np.mean(sla_history[-200:])\n"
"                best_reward = np.mean(rewards_history[-200:])\n"
"                no_improve_count = 0\n"
"                agent.save(f'{SAVE_DIR}/best_mixed.pth')\n"
"                if run_ctx:\n"
"                    mlflow.log_metrics({'best_cost': best_cost, 'best_sla': best_sla,\n"
"                                        'best_reward': best_reward}, step=episode)\n"
"                    try:\n"
"                        mlflow.log_artifact(f'{SAVE_DIR}/best_mixed.pth', artifact_path='models')\n"
"                    except Exception as _e:\n"
"                        print(f'Artifact upload skipped: {_e}')\n"
"            elif episode >= MIN_EPISODES:\n"
"                no_improve_count += 1\n"
"\n"
"        if run_ctx and (episode + 1) % LOG_EVERY == 0:\n"
"            metrics = {\n"
"                'reward':  float(np.mean(rewards_history[-LOG_EVERY:])),\n"
"                'cost':    float(np.mean(cost_history[-LOG_EVERY:])),\n"
"                'sla':     float(np.mean(sla_history[-LOG_EVERY:])),\n"
"                'loss':    float(np.mean(loss_history[-LOG_EVERY:])),\n"
"                'epsilon': float(agent.epsilon),\n"
"            }\n"
"            for n in ['stable', 'volatile', 'spike', 'az_divergence']:\n"
"                if per_scn_cost[n]:\n"
"                    metrics[f'cost_{n}'] = float(np.mean(per_scn_cost[n][-20:]))\n"
"                    metrics[f'sla_{n}']  = float(np.mean(per_scn_sla[n][-20:]))\n"
"            for i, n in enumerate(env.scenario_names):\n"
"                metrics[f'weight_{n}'] = float(env.weights[i])\n"
"            mlflow.log_metrics(metrics, step=episode)\n"
"\n"
"        if (episode + 1) % PRINT_EVERY == 0:\n"
"            avg_r = np.mean(rewards_history[-100:])\n"
"            avg_c = np.mean(cost_history[-100:])\n"
"            avg_s = np.mean(sla_history[-100:])\n"
"            elapsed = (time.time() - start_time) / 60\n"
"            bc = f'${best_cost:.1f}' if best_cost is not None else 'n/a'\n"
"            bs = f'{best_sla:.1%}' if best_sla is not None else 'n/a'\n"
"            scn_sum = ' '.join(\n"
"                f'{n[:3]}:${np.mean(per_scn_cost[n][-50:]):.0f}/{np.mean(per_scn_sla[n][-50:]):.0%}'\n"
"                for n in ['stable','volatile','spike','az_divergence'] if per_scn_cost[n]\n"
"            )\n"
"            w_str = ' '.join(f'{n[:3]}:{env.weights[i]:.2f}' for i, n in enumerate(env.scenario_names))\n"
"            print(f'Ep {episode+1:4d} | R:{avg_r:+7.1f} Cost:${avg_c:5.1f} SLA:{avg_s:.1%} '\n"
"                  f'Eps:{agent.epsilon:.3f} best:{bc}/{bs} | {scn_sum} | w:[{w_str}] | {elapsed:.1f}m')\n"
"\n"
"        if episode >= MIN_EPISODES and no_improve_count >= PATIENCE:\n"
"            print(f'Early stop ep {episode+1}. Best cost=${best_cost:.1f} SLA={best_sla:.1%}')\n"
"            break\n"
"\n"
"finally:\n"
"    agent.save(f'{SAVE_DIR}/final_mixed.pth')\n"
"    with open(f'{SAVE_DIR}/history_mixed.pkl', 'wb') as f:\n"
"        pickle.dump({\n"
"            'rewards': rewards_history, 'loss': loss_history,\n"
"            'epsilon': eps_history, 'cost': cost_history, 'sla': sla_history,\n"
"            'scenario': scenario_history,\n"
"            'per_scn_cost': dict(per_scn_cost), 'per_scn_sla': dict(per_scn_sla),\n"
"        }, f)\n"
"    if run_ctx:\n"
"        try:\n"
"            mlflow.log_artifact(f'{SAVE_DIR}/final_mixed.pth', artifact_path='models')\n"
"            mlflow.log_artifact(f'{SAVE_DIR}/history_mixed.pkl', artifact_path='history')\n"
"        except Exception as _e:\n"
"            print(f'Final artifact upload skipped: {_e}')\n"
"        mlflow.end_run()\n"
"        print('MLflow run ended.')\n"
"\n"
"# Register best model to MLflow Model Registry\n"
"if run_ctx and best_cost is not None:\n"
"    try:\n"
"        run_id = run_ctx.info.run_id\n"
"        model_uri = f'runs:/{run_id}/models/best_mixed.pth'\n"
"        mv = mlflow.register_model(model_uri=model_uri, name='Spot-RL-Agent')\n"
"        # Tag version with performance metrics\n"
"        client = mlflow.tracking.MlflowClient()\n"
"        client.set_model_version_tag(mv.name, mv.version, 'avg_cost',   f'{best_cost:.1f}')\n"
"        client.set_model_version_tag(mv.name, mv.version, 'avg_sla',    f'{best_sla:.3f}')\n"
"        client.set_model_version_tag(mv.name, mv.version, 'epsilon_end', f'{agent.epsilon:.4f}')\n"
"        client.set_model_version_tag(mv.name, mv.version, 'steps_done',  str(agent.steps_done))\n"
"        client.set_model_version_tag(mv.name, mv.version, 'resumed_from', RESUME_CHECKPOINT or 'scratch')\n"
"        print(f'Registered: Spot-RL-Agent v{mv.version} | cost=${best_cost:.1f} SLA={best_sla:.1%}')\n"
"    except Exception as _e:\n"
"        print(f'Model Registry skipped: {_e}')\n"
"\n"
"print(f'Done. Best: cost=${best_cost:.1f} SLA={best_sla:.1%} R={best_reward:+.1f}')\n"
),

cell(
"# Step 7: Plot training curves\n"
"import matplotlib.pyplot as plt\n"
"import pandas as pd\n"
"import numpy as np\n"
"\n"
"def smooth(data, w=100):\n"
"    return pd.Series(data).rolling(w, min_periods=1).mean().values\n"
"\n"
"fig, axes = plt.subplots(2, 3, figsize=(18, 9))\n"
"fig.suptitle('Generalist Agent -- Factored DQN on 4 mixed scenarios', fontsize=13)\n"
"\n"
"eps = range(1, len(rewards_history) + 1)\n"
"axes[0,0].plot(eps, rewards_history, alpha=0.15, color='steelblue')\n"
"axes[0,0].plot(eps, smooth(rewards_history), color='steelblue', lw=2)\n"
"axes[0,0].set_title('Reward (all scenarios)'); axes[0,0].grid(alpha=0.3)\n"
"\n"
"axes[0,1].plot(eps, cost_history, alpha=0.15, color='coral')\n"
"axes[0,1].plot(eps, smooth(cost_history), color='coral', lw=2)\n"
"axes[0,1].set_title('Cost ($) -- all scenarios'); axes[0,1].grid(alpha=0.3)\n"
"\n"
"axes[0,2].plot(eps, sla_history, alpha=0.15, color='green')\n"
"axes[0,2].plot(eps, smooth(sla_history), color='green', lw=2)\n"
"axes[0,2].axhline(0.95, color='red', linestyle='--', alpha=0.5)\n"
"axes[0,2].set_title('SLA -- all scenarios'); axes[0,2].grid(alpha=0.3)\n"
"\n"
"colors = {'stable':'#2ca02c','volatile':'#d62728','spike':'#ff7f0e','az_divergence':'#9467bd'}\n"
"for scn, col in colors.items():\n"
"    if scn in per_scn_cost and len(per_scn_cost[scn]) > 10:\n"
"        xs = np.arange(len(per_scn_cost[scn]))\n"
"        axes[1,0].plot(xs, smooth(per_scn_cost[scn], 50), color=col, lw=2, label=scn)\n"
"        axes[1,1].plot(xs, smooth(per_scn_sla[scn], 50), color=col, lw=2, label=scn)\n"
"\n"
"axes[1,0].set_title('Cost per scenario'); axes[1,0].grid(alpha=0.3); axes[1,0].legend(fontsize=8)\n"
"axes[1,1].set_title('SLA per scenario'); axes[1,1].grid(alpha=0.3); axes[1,1].legend(fontsize=8)\n"
"axes[1,1].axhline(0.95, color='red', linestyle='--', alpha=0.5)\n"
"axes[1,2].plot(eps, eps_history, color='orange', lw=2)\n"
"axes[1,2].set_title('Epsilon'); axes[1,2].grid(alpha=0.3)\n"
"\n"
"plt.tight_layout()\n"
"plt.savefig(f'{SAVE_DIR}/training_curves.png', dpi=100)\n"
"plt.show()\n"
"\n"
"print('Per-scenario (last 100 eps):')\n"
"for scn in ['stable','volatile','spike','az_divergence']:\n"
"    if per_scn_cost[scn]:\n"
"        c = np.mean(per_scn_cost[scn][-100:])\n"
"        s = np.mean(per_scn_sla[scn][-100:])\n"
"        print(f'  {scn:15s}: cost=${c:6.2f}  SLA={s:.1%}')\n"
),

cell(
"# Step 8: List output files\n"
"import os\n"
"print('Files saved:')\n"
"for f in sorted(os.listdir(SAVE_DIR)):\n"
"    size = os.path.getsize(f'{SAVE_DIR}/{f}') / 1024\n"
"    print(f'  {f}: {size:.0f} KB')\n"
),
]

with open(path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print('Rebuilt notebook. Cell count:', len(nb['cells']))
for i, c in enumerate(nb['cells']):
    s = c['source'] if isinstance(c['source'], str) else ''.join(c['source'])
    print(f'  [{i}] {s[:65].strip()}')
